site_name: ShopEat
repo_url: https://github.com/sylvanld/shopeat
repo_name: sylvanld/shopeat
theme:
  name: material
  palette:
    primary: amber
    accent: orange
plugins:
  - mike
  - search
  - swagger-ui-tag
extra:
  version:
    default: 0.0.1
    provider: mike
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - assets/main.css
