on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.11
          cache: pip

      - name: Install test dependencies
        run: pip install -r requirements/tests.txt

      - name: Run unit tests
        run: python -m pytest tests/
