on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.11
      - name: "Install test dependencies"
        run: pip install -r requirements/tests.txt
      - name: "Run unit tests"
        run: python -m pytest tests/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.11
      - name: "Install test dependencies"
        run: pip install -r requirements/tests.txt
      - name: "Run unit tests"
        run: python -m pylint shopeat || pylint-exit $?
