on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


env:
  DOCKER_IMAGE_NAME: shopeat
  DOCKER_IMAGE_TAG: ${GITHUB_REF/refs\/tags\//}
  DOCKER_ORG_NAME: sylvanld
  
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_REGISTRY_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
  DOCKER_REGISTRY_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"


jobs:
  publish-image:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Login to docker registry      
        run: echo -n "${{ env.DOCKER_REGISTRY_PASSWORD }}" | docker login --username "${{ env.DOCKER_REGISTRY_USERNAME }}" --password-stdin ${{ env.DOCKER_REGISTRY_URL }}
      
      # Install QEMU to emulate different architecture (required to use buildx for ARM)
      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v1

      # Install docker buildx to build image for multiple architectures
      - name: Docker Setup Buildx
        if: success()
        uses: docker/setup-buildx-action@v1.3.0
        with:
          # Buildx version. (eg. v0.3.0)
          version: v0.3.0
          
      # build and publish image for multiple architectures
      - name: Build and publish
        if: success()
        run: docker buildx build --platform linux/amd64,linux/arm64 --output type=image,push=true -t ${{env.DOCKER_REGISTRY_URL}}/${{env.DOCKER_ORG_NAME}}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} -t ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_ORG_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .

  publish-documentation:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.11

      - name: "Install docs dependencies"
        run: pip install -r requirements/docs.txt
      
      - name: "Build doc and update github pages"
        run: |-
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          mike deploy --push --update-aliases ${{ env.DOCKER_IMAGE_TAG }} latest
